package v1

import (
	"github.com/labstack/echo/v4"
	"github.com/qkhuyit/rts/rts-api/internal/app/core/models"
	"github.com/qkhuyit/rts/rts-api/internal/app/core/web"
)

type SystemController interface {
	GetSystemInfo(ctx echo.Context) error
}

type systemControllerImpl struct {
}

func NewSystemController() SystemController {
	return &systemControllerImpl{}
}

func (c *systemControllerImpl) GetSystemInfo(ctx echo.Context) error {
	return web.SendOK(&models.SystemInfoModel{
		Name:        "RTS",
		Title:       "Retail System",
		Description: "",
		Status:      1,
		Menus: []models.SystemMenuModel{
			{
				ID:        12,
				Path:      "/document",
				Component: "",
				Name:      "Document",
				Redirect:  "https://www.typeorm.org/",
				Meta: &models.SystemMenuMetaModel{
					Title:       "文档",
					Icon:        "ion:tv-outline",
					IsExt:       false,
					ExtOpenMode: 1,
					Type:        0,
					OrderNo:     2,
					Show:        1,
					ActiveMenu:  nil,
					Status:      1,
					KeepAlive:   0,
				},
				Children: []models.SystemMenuModel{
					{
						ID:   14,
						Path: "https://www.typeorm.org/",
						Name: "Typeorm中文文档(外链)",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Typeorm中文文档(外链)",
							Icon:        "",
							IsExt:       true,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     3,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:   15,
						Path: "https://docs.nestjs.cn/",
						Name: "Nest.js中文文档(内嵌)",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Nest.js中文文档(内嵌)",
							Icon:        "",
							IsExt:       true,
							ExtOpenMode: 2,
							Type:        1,
							OrderNo:     4,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:   112,
						Path: "https://antdv.com/components/overview-cn",
						Name: "antdv文档(内嵌)",
						Meta: &models.SystemMenuMetaModel{
							Title:       "antdv文档(内嵌)",
							Icon:        "",
							IsExt:       true,
							ExtOpenMode: 2,
							Type:        1,
							OrderNo:     255,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
				},
			},
			{
				ID:        1,
				Path:      "/system",
				Component: "",
				Name:      "System Management",
				Redirect:  "/system/user",
				Meta: &models.SystemMenuMetaModel{
					Title:       "System Management",
					Icon:        "ant-design:setting-outlined",
					IsExt:       false,
					ExtOpenMode: 1,
					Type:        0,
					OrderNo:     254,
					Show:        1,
					ActiveMenu:  nil,
					Status:      1,
					KeepAlive:   0,
				},
				Children: []models.SystemMenuModel{
					{
						ID:        2,
						Path:      "/system/user",
						Name:      "用户管理",
						Component: "system/user/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "用户管理",
							Icon:        "ant-design:user-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     0,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        3,
						Path:      "/system/role",
						Name:      "角色管理",
						Component: "system/role/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "角色管理",
							Icon:        "ep:user",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     1,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        4,
						Path:      "/system/menu",
						Name:      "菜单管理",
						Component: "system/menu/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "菜单管理",
							Icon:        "ep:menu",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     2,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        61,
						Path:      "/system/dept",
						Name:      "部门管理",
						Component: "system/dept/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "部门管理",
							Icon:        "ant-design:deployment-unit-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     3,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        56,
						Path:      "/system/dict-type",
						Name:      "字典管理",
						Component: "system/dict-type/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "字典管理",
							Icon:        "ant-design:book-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     4,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        5,
						Path:      "/system/monitor",
						Component: "",
						Name:      "系统监控",
						Meta: &models.SystemMenuMetaModel{
							Title:       "系统监控",
							Icon:        "ep:monitor",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        0,
							OrderNo:     5,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
						Redirect: "/system/monitor/online",
						Children: []models.SystemMenuModel{
							{
								ID:        6,
								Path:      "/system/monitor/online",
								Name:      "在线用户",
								Component: "system/monitor/online/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "在线用户",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        7,
								Path:      "/sys/monitor/login-log",
								Name:      "登录日志",
								Component: "system/monitor/log/login/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "登录日志",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        68,
								Path:      "/health",
								Name:      "健康检查",
								Component: "",
								Meta: &models.SystemMenuMetaModel{
									Title:       "健康检查",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     4,
									Show:        0,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        8,
								Path:      "/system/monitor/serve",
								Name:      "服务监控",
								Component: "system/monitor/serve/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "服务监控",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     4,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
						},
					},
					{
						ID:        9,
						Path:      "/system/schedule",
						Component: "",
						Name:      "任务调度",
						Meta: &models.SystemMenuMetaModel{
							Title:       "任务调度",
							Icon:        "ant-design:schedule-filled",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        0,
							OrderNo:     6,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
						Redirect: "/system/task",
						Children: []models.SystemMenuModel{
							{
								ID:        10,
								Path:      "/system/task",
								Name:      "任务管理",
								Component: "system/schedule/task/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "任务管理",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        11,
								Path:      "/system/task/log",
								Name:      "任务日志",
								Component: "system/schedule/log/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "任务日志",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
						},
					},
					{
						ID:        107,
						Path:      "system/dict-item/:id",
						Name:      "字典项管理",
						Component: "system/dict-item/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "字典项管理",
							Icon:        "ant-design:facebook-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     255,
							Show:        0,
							ActiveMenu:  "字典管理",
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        86,
						Path:      "/param-config",
						Name:      "参数配置",
						Component: "system/param-config/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "参数配置",
							Icon:        "ep:edit",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     255,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
				},
			},
			{
				ID:        48,
				Path:      "/tool",
				Component: "",
				Name:      "系统工具",
				Meta: &models.SystemMenuMetaModel{
					Title:       "系统工具",
					Icon:        "ant-design:tool-outlined",
					IsExt:       false,
					ExtOpenMode: 1,
					Type:        0,
					OrderNo:     254,
					Show:        1,
					ActiveMenu:  nil,
					Status:      1,
					KeepAlive:   0,
				},
				Redirect: "/tool/email",
				Children: []models.SystemMenuModel{
					{
						ID:        49,
						Path:      "/tool/email",
						Name:      "邮件工具",
						Component: "tool/email/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "邮件工具",
							Icon:        "ant-design:send-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     1,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        51,
						Path:      "/tool/storage",
						Name:      "存储管理",
						Component: "tool/storage/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "存储管理",
							Icon:        "ant-design:appstore-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     2,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
				},
			},
		},
	}, ctx)
}
