package v1

import (
	"github.com/labstack/echo/v4"
	"github.com/qkhuyit/rts/rts-api/internal/app/core/models"
	"github.com/qkhuyit/rts/rts-api/internal/app/core/web"
)

type SystemController interface {
	GetSystemInfo(ctx echo.Context) error
}

type systemControllerImpl struct {
}

func NewSystemController() SystemController {
	return &systemControllerImpl{}
}

func (c *systemControllerImpl) GetSystemInfo(ctx echo.Context) error {
	return web.SendOK(&models.SystemInfoModel{
		Name:        "RTS",
		Title:       "Retail System",
		Description: "",
		Status:      1,
		Menus: []models.SystemMenuModel{
			{
				ID:        1,
				Path:      "/system",
				Component: "",
				Name:      "System Management",
				Redirect:  "/system/user",
				Meta: &models.SystemMenuMetaModel{
					Title:       "System Management",
					Icon:        "ant-design:setting-outlined",
					IsExt:       false,
					ExtOpenMode: 1,
					Type:        0,
					OrderNo:     254,
					Show:        1,
					ActiveMenu:  nil,
					Status:      1,
					KeepAlive:   0,
				},
				Children: []models.SystemMenuModel{
					{
						ID:        2,
						Path:      "/system/user",
						Name:      "User Management",
						Component: "system/user/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "User Management",
							Icon:        "ant-design:user-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     0,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        2,
						Path:      "/system/group",
						Name:      "Group Management",
						Component: "system/group/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Group Management",
							Icon:        "ant-design:group-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     0,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        3,
						Path:      "/system/role",
						Name:      "Role Management",
						Component: "system/role/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Role Management",
							Icon:        "ep:user",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     1,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        4,
						Path:      "/system/menu",
						Name:      "Menu Management",
						Component: "system/menu/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Menu Management",
							Icon:        "ep:menu",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     2,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        61,
						Path:      "/system/dept",
						Name:      "Department Management",
						Component: "system/dept/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Department Management",
							Icon:        "ant-design:deployment-unit-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     3,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        56,
						Path:      "/system/dict-type",
						Name:      "Dictionary Management",
						Component: "system/dict-type/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Dictionary Management",
							Icon:        "ant-design:book-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     4,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        5,
						Path:      "/system/monitor",
						Component: "",
						Name:      "System Monitoring",
						Meta: &models.SystemMenuMetaModel{
							Title:       "System Monitoring",
							Icon:        "ep:monitor",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        0,
							OrderNo:     5,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
						Redirect: "/system/monitor/online",
						Children: []models.SystemMenuModel{
							{
								ID:        6,
								Path:      "/system/monitor/online",
								Name:      "Online User",
								Component: "system/monitor/online/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Online User",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        7,
								Path:      "/sys/monitor/login-log",
								Name:      "Login Log",
								Component: "system/monitor/log/login/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Login Log",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        68,
								Path:      "/health",
								Name:      "Health Examination",
								Component: "",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Health Examination",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     4,
									Show:        0,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        8,
								Path:      "/system/monitor/serve",
								Name:      "Service Monitoring",
								Component: "system/monitor/serve/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Service Monitoring",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     4,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
						},
					},
					{
						ID:        9,
						Path:      "/system/schedule",
						Component: "",
						Name:      "Task Scheduling",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Task Scheduling",
							Icon:        "ant-design:schedule-filled",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        0,
							OrderNo:     6,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
						Redirect: "/system/task",
						Children: []models.SystemMenuModel{
							{
								ID:        10,
								Path:      "/system/task",
								Name:      "Task Management",
								Component: "system/schedule/task/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Task Management",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
							{
								ID:        11,
								Path:      "/system/task/log",
								Name:      "Mission Log",
								Component: "system/schedule/log/index",
								Meta: &models.SystemMenuMetaModel{
									Title:       "Mission Log",
									Icon:        "",
									IsExt:       false,
									ExtOpenMode: 1,
									Type:        1,
									OrderNo:     0,
									Show:        1,
									ActiveMenu:  nil,
									Status:      1,
									KeepAlive:   0,
								},
							},
						},
					},
					{
						ID:        107,
						Path:      "system/dict-item/:id",
						Name:      "Dictionary Item Management",
						Component: "system/dict-item/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Dictionary Item Management",
							Icon:        "ant-design:facebook-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     255,
							Show:        0,
							ActiveMenu:  "字典管理",
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        86,
						Path:      "/param-config",
						Name:      "Parameter Configuration",
						Component: "system/param-config/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Parameter Configuration",
							Icon:        "ep:edit",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     255,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
				},
			},
			{
				ID:        48,
				Path:      "/tool",
				Component: "",
				Name:      "System Tool",
				Meta: &models.SystemMenuMetaModel{
					Title:       "System Tool",
					Icon:        "ant-design:tool-outlined",
					IsExt:       false,
					ExtOpenMode: 1,
					Type:        0,
					OrderNo:     254,
					Show:        1,
					ActiveMenu:  nil,
					Status:      1,
					KeepAlive:   0,
				},
				Redirect: "/tool/email",
				Children: []models.SystemMenuModel{
					{
						ID:        49,
						Path:      "/tool/email",
						Name:      "Email Tool",
						Component: "tool/email/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Email Tool",
							Icon:        "ant-design:send-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     1,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
					{
						ID:        51,
						Path:      "/tool/storage",
						Name:      "Storage Management",
						Component: "tool/storage/index",
						Meta: &models.SystemMenuMetaModel{
							Title:       "Storage Management",
							Icon:        "ant-design:appstore-outlined",
							IsExt:       false,
							ExtOpenMode: 1,
							Type:        1,
							OrderNo:     2,
							Show:        1,
							ActiveMenu:  nil,
							Status:      1,
							KeepAlive:   0,
						},
					},
				},
			},
		},
	}, ctx)
}
